// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: LinuxChatApp.proto

package LinuxChatAppPb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LinuxChatAppService_CreateChatRoom_FullMethodName = "/linuxChatApp.LinuxChatAppService/CreateChatRoom"
	LinuxChatAppService_JoinChatRoom_FullMethodName   = "/linuxChatApp.LinuxChatAppService/JoinChatRoom"
	LinuxChatAppService_LeaveChatRoom_FullMethodName  = "/linuxChatApp.LinuxChatAppService/LeaveChatRoom"
	LinuxChatAppService_SendMessage_FullMethodName    = "/linuxChatApp.LinuxChatAppService/SendMessage"
)

// LinuxChatAppServiceClient is the client API for LinuxChatAppService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LinuxChatAppServiceClient interface {
	CreateChatRoom(ctx context.Context, in *ChatRoomRequest, opts ...grpc.CallOption) (*ChatRoomResponse, error)
	JoinChatRoom(ctx context.Context, in *ChatRoomRequest, opts ...grpc.CallOption) (*ChatRoomResponse, error)
	LeaveChatRoom(ctx context.Context, in *ChatRoomRequest, opts ...grpc.CallOption) (*ChatRoomResponse, error)
	SendMessage(ctx context.Context, opts ...grpc.CallOption) (LinuxChatAppService_SendMessageClient, error)
}

type linuxChatAppServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLinuxChatAppServiceClient(cc grpc.ClientConnInterface) LinuxChatAppServiceClient {
	return &linuxChatAppServiceClient{cc}
}

func (c *linuxChatAppServiceClient) CreateChatRoom(ctx context.Context, in *ChatRoomRequest, opts ...grpc.CallOption) (*ChatRoomResponse, error) {
	out := new(ChatRoomResponse)
	err := c.cc.Invoke(ctx, LinuxChatAppService_CreateChatRoom_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linuxChatAppServiceClient) JoinChatRoom(ctx context.Context, in *ChatRoomRequest, opts ...grpc.CallOption) (*ChatRoomResponse, error) {
	out := new(ChatRoomResponse)
	err := c.cc.Invoke(ctx, LinuxChatAppService_JoinChatRoom_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linuxChatAppServiceClient) LeaveChatRoom(ctx context.Context, in *ChatRoomRequest, opts ...grpc.CallOption) (*ChatRoomResponse, error) {
	out := new(ChatRoomResponse)
	err := c.cc.Invoke(ctx, LinuxChatAppService_LeaveChatRoom_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linuxChatAppServiceClient) SendMessage(ctx context.Context, opts ...grpc.CallOption) (LinuxChatAppService_SendMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &LinuxChatAppService_ServiceDesc.Streams[0], LinuxChatAppService_SendMessage_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &linuxChatAppServiceSendMessageClient{stream}
	return x, nil
}

type LinuxChatAppService_SendMessageClient interface {
	Send(*MessageRequest) error
	Recv() (*ChatLog, error)
	grpc.ClientStream
}

type linuxChatAppServiceSendMessageClient struct {
	grpc.ClientStream
}

func (x *linuxChatAppServiceSendMessageClient) Send(m *MessageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *linuxChatAppServiceSendMessageClient) Recv() (*ChatLog, error) {
	m := new(ChatLog)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LinuxChatAppServiceServer is the server API for LinuxChatAppService service.
// All implementations must embed UnimplementedLinuxChatAppServiceServer
// for forward compatibility
type LinuxChatAppServiceServer interface {
	CreateChatRoom(context.Context, *ChatRoomRequest) (*ChatRoomResponse, error)
	JoinChatRoom(context.Context, *ChatRoomRequest) (*ChatRoomResponse, error)
	LeaveChatRoom(context.Context, *ChatRoomRequest) (*ChatRoomResponse, error)
	SendMessage(LinuxChatAppService_SendMessageServer) error
	mustEmbedUnimplementedLinuxChatAppServiceServer()
}

// UnimplementedLinuxChatAppServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLinuxChatAppServiceServer struct {
}

func (UnimplementedLinuxChatAppServiceServer) CreateChatRoom(context.Context, *ChatRoomRequest) (*ChatRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChatRoom not implemented")
}
func (UnimplementedLinuxChatAppServiceServer) JoinChatRoom(context.Context, *ChatRoomRequest) (*ChatRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinChatRoom not implemented")
}
func (UnimplementedLinuxChatAppServiceServer) LeaveChatRoom(context.Context, *ChatRoomRequest) (*ChatRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveChatRoom not implemented")
}
func (UnimplementedLinuxChatAppServiceServer) SendMessage(LinuxChatAppService_SendMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedLinuxChatAppServiceServer) mustEmbedUnimplementedLinuxChatAppServiceServer() {}

// UnsafeLinuxChatAppServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinuxChatAppServiceServer will
// result in compilation errors.
type UnsafeLinuxChatAppServiceServer interface {
	mustEmbedUnimplementedLinuxChatAppServiceServer()
}

func RegisterLinuxChatAppServiceServer(s grpc.ServiceRegistrar, srv LinuxChatAppServiceServer) {
	s.RegisterService(&LinuxChatAppService_ServiceDesc, srv)
}

func _LinuxChatAppService_CreateChatRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinuxChatAppServiceServer).CreateChatRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinuxChatAppService_CreateChatRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinuxChatAppServiceServer).CreateChatRoom(ctx, req.(*ChatRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinuxChatAppService_JoinChatRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinuxChatAppServiceServer).JoinChatRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinuxChatAppService_JoinChatRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinuxChatAppServiceServer).JoinChatRoom(ctx, req.(*ChatRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinuxChatAppService_LeaveChatRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinuxChatAppServiceServer).LeaveChatRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinuxChatAppService_LeaveChatRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinuxChatAppServiceServer).LeaveChatRoom(ctx, req.(*ChatRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinuxChatAppService_SendMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LinuxChatAppServiceServer).SendMessage(&linuxChatAppServiceSendMessageServer{stream})
}

type LinuxChatAppService_SendMessageServer interface {
	Send(*ChatLog) error
	Recv() (*MessageRequest, error)
	grpc.ServerStream
}

type linuxChatAppServiceSendMessageServer struct {
	grpc.ServerStream
}

func (x *linuxChatAppServiceSendMessageServer) Send(m *ChatLog) error {
	return x.ServerStream.SendMsg(m)
}

func (x *linuxChatAppServiceSendMessageServer) Recv() (*MessageRequest, error) {
	m := new(MessageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LinuxChatAppService_ServiceDesc is the grpc.ServiceDesc for LinuxChatAppService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LinuxChatAppService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "linuxChatApp.LinuxChatAppService",
	HandlerType: (*LinuxChatAppServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChatRoom",
			Handler:    _LinuxChatAppService_CreateChatRoom_Handler,
		},
		{
			MethodName: "JoinChatRoom",
			Handler:    _LinuxChatAppService_JoinChatRoom_Handler,
		},
		{
			MethodName: "LeaveChatRoom",
			Handler:    _LinuxChatAppService_LeaveChatRoom_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendMessage",
			Handler:       _LinuxChatAppService_SendMessage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "LinuxChatApp.proto",
}
