// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: LinuxChatApp.proto

package LinuxChatAppPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateChatRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName     string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	ChatRoomName string   `protobuf:"bytes,2,opt,name=chatRoomName,proto3" json:"chatRoomName,omitempty"`
	Users        []string `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *CreateChatRoomRequest) Reset() {
	*x = CreateChatRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinuxChatApp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatRoomRequest) ProtoMessage() {}

func (x *CreateChatRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LinuxChatApp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateChatRoomRequest) Descriptor() ([]byte, []int) {
	return file_LinuxChatApp_proto_rawDescGZIP(), []int{0}
}

func (x *CreateChatRoomRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CreateChatRoomRequest) GetChatRoomName() string {
	if x != nil {
		return x.ChatRoomName
	}
	return ""
}

func (x *CreateChatRoomRequest) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

type CreateChatRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostUserName string `protobuf:"bytes,1,opt,name=hostUserName,proto3" json:"hostUserName,omitempty"`
	ChatRoomName string `protobuf:"bytes,2,opt,name=chatRoomName,proto3" json:"chatRoomName,omitempty"`
}

func (x *CreateChatRoomResponse) Reset() {
	*x = CreateChatRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinuxChatApp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatRoomResponse) ProtoMessage() {}

func (x *CreateChatRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_LinuxChatApp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateChatRoomResponse) Descriptor() ([]byte, []int) {
	return file_LinuxChatApp_proto_rawDescGZIP(), []int{1}
}

func (x *CreateChatRoomResponse) GetHostUserName() string {
	if x != nil {
		return x.HostUserName
	}
	return ""
}

func (x *CreateChatRoomResponse) GetChatRoomName() string {
	if x != nil {
		return x.ChatRoomName
	}
	return ""
}

type JoinChatRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName     string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	ChatRoomName string `protobuf:"bytes,2,opt,name=chatRoomName,proto3" json:"chatRoomName,omitempty"`
}

func (x *JoinChatRoomRequest) Reset() {
	*x = JoinChatRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinuxChatApp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinChatRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinChatRoomRequest) ProtoMessage() {}

func (x *JoinChatRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LinuxChatApp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinChatRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinChatRoomRequest) Descriptor() ([]byte, []int) {
	return file_LinuxChatApp_proto_rawDescGZIP(), []int{2}
}

func (x *JoinChatRoomRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *JoinChatRoomRequest) GetChatRoomName() string {
	if x != nil {
		return x.ChatRoomName
	}
	return ""
}

type JoinChatRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *JoinChatRoomResponse) Reset() {
	*x = JoinChatRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinuxChatApp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinChatRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinChatRoomResponse) ProtoMessage() {}

func (x *JoinChatRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_LinuxChatApp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinChatRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinChatRoomResponse) Descriptor() ([]byte, []int) {
	return file_LinuxChatApp_proto_rawDescGZIP(), []int{3}
}

func (x *JoinChatRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LeaveChatRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName     string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	ChatRoomName string `protobuf:"bytes,2,opt,name=chatRoomName,proto3" json:"chatRoomName,omitempty"`
}

func (x *LeaveChatRoomRequest) Reset() {
	*x = LeaveChatRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinuxChatApp_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveChatRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveChatRoomRequest) ProtoMessage() {}

func (x *LeaveChatRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LinuxChatApp_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveChatRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveChatRoomRequest) Descriptor() ([]byte, []int) {
	return file_LinuxChatApp_proto_rawDescGZIP(), []int{4}
}

func (x *LeaveChatRoomRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LeaveChatRoomRequest) GetChatRoomName() string {
	if x != nil {
		return x.ChatRoomName
	}
	return ""
}

type LeaveChatRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *LeaveChatRoomResponse) Reset() {
	*x = LeaveChatRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinuxChatApp_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveChatRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveChatRoomResponse) ProtoMessage() {}

func (x *LeaveChatRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_LinuxChatApp_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveChatRoomResponse.ProtoReflect.Descriptor instead.
func (*LeaveChatRoomResponse) Descriptor() ([]byte, []int) {
	return file_LinuxChatApp_proto_rawDescGZIP(), []int{5}
}

func (x *LeaveChatRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MessageRow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName  string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	TimeStamp string `protobuf:"bytes,2,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	Message   string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *MessageRow) Reset() {
	*x = MessageRow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinuxChatApp_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRow) ProtoMessage() {}

func (x *MessageRow) ProtoReflect() protoreflect.Message {
	mi := &file_LinuxChatApp_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRow.ProtoReflect.Descriptor instead.
func (*MessageRow) Descriptor() ([]byte, []int) {
	return file_LinuxChatApp_proto_rawDescGZIP(), []int{6}
}

func (x *MessageRow) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *MessageRow) GetTimeStamp() string {
	if x != nil {
		return x.TimeStamp
	}
	return ""
}

func (x *MessageRow) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatRoomName string `protobuf:"bytes,1,opt,name=chatRoomName,proto3" json:"chatRoomName,omitempty"`
	ChatRow      string `protobuf:"bytes,2,opt,name=ChatRow,proto3" json:"ChatRow,omitempty"`
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinuxChatApp_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_LinuxChatApp_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_LinuxChatApp_proto_rawDescGZIP(), []int{7}
}

func (x *MessageResponse) GetChatRoomName() string {
	if x != nil {
		return x.ChatRoomName
	}
	return ""
}

func (x *MessageResponse) GetChatRow() string {
	if x != nil {
		return x.ChatRow
	}
	return ""
}

type MessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName      string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	OtherUserName string `protobuf:"bytes,2,opt,name=otherUserName,proto3" json:"otherUserName,omitempty"`
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	TimeStamp     string `protobuf:"bytes,4,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
}

func (x *MessageRequest) Reset() {
	*x = MessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinuxChatApp_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequest) ProtoMessage() {}

func (x *MessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LinuxChatApp_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequest.ProtoReflect.Descriptor instead.
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return file_LinuxChatApp_proto_rawDescGZIP(), []int{8}
}

func (x *MessageRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *MessageRequest) GetOtherUserName() string {
	if x != nil {
		return x.OtherUserName
	}
	return ""
}

func (x *MessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MessageRequest) GetTimeStamp() string {
	if x != nil {
		return x.TimeStamp
	}
	return ""
}

type ViewListOfUsersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ViewListOfUsersRequest) Reset() {
	*x = ViewListOfUsersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinuxChatApp_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewListOfUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewListOfUsersRequest) ProtoMessage() {}

func (x *ViewListOfUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LinuxChatApp_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewListOfUsersRequest.ProtoReflect.Descriptor instead.
func (*ViewListOfUsersRequest) Descriptor() ([]byte, []int) {
	return file_LinuxChatApp_proto_rawDescGZIP(), []int{9}
}

type ViewListOfUsersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []string `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *ViewListOfUsersResponse) Reset() {
	*x = ViewListOfUsersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinuxChatApp_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewListOfUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewListOfUsersResponse) ProtoMessage() {}

func (x *ViewListOfUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_LinuxChatApp_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewListOfUsersResponse.ProtoReflect.Descriptor instead.
func (*ViewListOfUsersResponse) Descriptor() ([]byte, []int) {
	return file_LinuxChatApp_proto_rawDescGZIP(), []int{10}
}

func (x *ViewListOfUsersResponse) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

type ViewListOfChatRoomsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ViewListOfChatRoomsRequest) Reset() {
	*x = ViewListOfChatRoomsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinuxChatApp_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewListOfChatRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewListOfChatRoomsRequest) ProtoMessage() {}

func (x *ViewListOfChatRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LinuxChatApp_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewListOfChatRoomsRequest.ProtoReflect.Descriptor instead.
func (*ViewListOfChatRoomsRequest) Descriptor() ([]byte, []int) {
	return file_LinuxChatApp_proto_rawDescGZIP(), []int{11}
}

type ViewListOfChatRoomsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatRoomNames []string `protobuf:"bytes,1,rep,name=chatRoomNames,proto3" json:"chatRoomNames,omitempty"`
}

func (x *ViewListOfChatRoomsResponse) Reset() {
	*x = ViewListOfChatRoomsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinuxChatApp_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewListOfChatRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewListOfChatRoomsResponse) ProtoMessage() {}

func (x *ViewListOfChatRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_LinuxChatApp_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewListOfChatRoomsResponse.ProtoReflect.Descriptor instead.
func (*ViewListOfChatRoomsResponse) Descriptor() ([]byte, []int) {
	return file_LinuxChatApp_proto_rawDescGZIP(), []int{12}
}

func (x *ViewListOfChatRoomsResponse) GetChatRoomNames() []string {
	if x != nil {
		return x.ChatRoomNames
	}
	return nil
}

var File_LinuxChatApp_proto protoreflect.FileDescriptor

var file_LinuxChatApp_proto_rawDesc = []byte{
	0x0a, 0x12, 0x4c, 0x69, 0x6e, 0x75, 0x78, 0x43, 0x68, 0x61, 0x74, 0x41, 0x70, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x43, 0x68, 0x61, 0x74, 0x41,
	0x70, 0x70, 0x22, 0x6d, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63,
	0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x75,
	0x73, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x22, 0x60, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x68,
	0x6f, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x68, 0x6f, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x55, 0x0a, 0x13, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x74, 0x52, 0x6f,
	0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x68,
	0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x30, 0x0a, 0x14, 0x4a, 0x6f,
	0x69, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x56, 0x0a, 0x14,
	0x4c, 0x65, 0x61, 0x76, 0x65, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x31, 0x0a, 0x15, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x43, 0x68, 0x61,
	0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x60, 0x0a, 0x0a, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x6f, 0x77, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4f, 0x0a, 0x0f, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c,
	0x63, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x63, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x77, 0x22, 0x8a, 0x01, 0x0a, 0x0e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x6f, 0x74, 0x68,
	0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x18, 0x0a, 0x16, 0x56, 0x69, 0x65, 0x77, 0x4c,
	0x69, 0x73, 0x74, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x2f, 0x0a, 0x17, 0x56, 0x69, 0x65, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x22, 0x1c, 0x0a, 0x1a, 0x56, 0x69, 0x65, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66,
	0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x43, 0x0a, 0x1b, 0x56, 0x69, 0x65, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x43, 0x68,
	0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x24, 0x0a, 0x0d, 0x63, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x32, 0xcb, 0x04, 0x0a, 0x13, 0x4c, 0x69, 0x6e, 0x75, 0x78, 0x43,
	0x68, 0x61, 0x74, 0x41, 0x70, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a,
	0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x12,
	0x23, 0x2e, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x43, 0x68, 0x61, 0x74, 0x41, 0x70, 0x70, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x43, 0x68, 0x61, 0x74,
	0x41, 0x70, 0x70, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f,
	0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x0c,
	0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x21, 0x2e, 0x6c,
	0x69, 0x6e, 0x75, 0x78, 0x43, 0x68, 0x61, 0x74, 0x41, 0x70, 0x70, 0x2e, 0x4a, 0x6f, 0x69, 0x6e,
	0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x43, 0x68, 0x61, 0x74, 0x41, 0x70, 0x70, 0x2e, 0x4a,
	0x6f, 0x69, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x0d, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x43, 0x68,
	0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x22, 0x2e, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x43, 0x68,
	0x61, 0x74, 0x41, 0x70, 0x70, 0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x43, 0x68, 0x61, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x6c, 0x69, 0x6e,
	0x75, 0x78, 0x43, 0x68, 0x61, 0x74, 0x41, 0x70, 0x70, 0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x43,
	0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x50, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x1c, 0x2e, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x43, 0x68, 0x61, 0x74, 0x41, 0x70, 0x70, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x43, 0x68, 0x61, 0x74, 0x41, 0x70, 0x70, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28,
	0x01, 0x30, 0x01, 0x12, 0x60, 0x0a, 0x0f, 0x56, 0x69, 0x65, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x4f,
	0x66, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x24, 0x2e, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x43, 0x68,
	0x61, 0x74, 0x41, 0x70, 0x70, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6c,
	0x69, 0x6e, 0x75, 0x78, 0x43, 0x68, 0x61, 0x74, 0x41, 0x70, 0x70, 0x2e, 0x56, 0x69, 0x65, 0x77,
	0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6c, 0x0a, 0x13, 0x56, 0x69, 0x65, 0x77, 0x4c, 0x69, 0x73,
	0x74, 0x4f, 0x66, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x28, 0x2e, 0x6c,
	0x69, 0x6e, 0x75, 0x78, 0x43, 0x68, 0x61, 0x74, 0x41, 0x70, 0x70, 0x2e, 0x56, 0x69, 0x65, 0x77,
	0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x43, 0x68,
	0x61, 0x74, 0x41, 0x70, 0x70, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66,
	0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x2f, 0x4c, 0x69, 0x6e, 0x75, 0x78, 0x43, 0x68, 0x61,
	0x74, 0x41, 0x70, 0x70, 0x50, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_LinuxChatApp_proto_rawDescOnce sync.Once
	file_LinuxChatApp_proto_rawDescData = file_LinuxChatApp_proto_rawDesc
)

func file_LinuxChatApp_proto_rawDescGZIP() []byte {
	file_LinuxChatApp_proto_rawDescOnce.Do(func() {
		file_LinuxChatApp_proto_rawDescData = protoimpl.X.CompressGZIP(file_LinuxChatApp_proto_rawDescData)
	})
	return file_LinuxChatApp_proto_rawDescData
}

var file_LinuxChatApp_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_LinuxChatApp_proto_goTypes = []interface{}{
	(*CreateChatRoomRequest)(nil),       // 0: linuxChatApp.CreateChatRoomRequest
	(*CreateChatRoomResponse)(nil),      // 1: linuxChatApp.CreateChatRoomResponse
	(*JoinChatRoomRequest)(nil),         // 2: linuxChatApp.JoinChatRoomRequest
	(*JoinChatRoomResponse)(nil),        // 3: linuxChatApp.JoinChatRoomResponse
	(*LeaveChatRoomRequest)(nil),        // 4: linuxChatApp.LeaveChatRoomRequest
	(*LeaveChatRoomResponse)(nil),       // 5: linuxChatApp.LeaveChatRoomResponse
	(*MessageRow)(nil),                  // 6: linuxChatApp.MessageRow
	(*MessageResponse)(nil),             // 7: linuxChatApp.MessageResponse
	(*MessageRequest)(nil),              // 8: linuxChatApp.MessageRequest
	(*ViewListOfUsersRequest)(nil),      // 9: linuxChatApp.ViewListOfUsersRequest
	(*ViewListOfUsersResponse)(nil),     // 10: linuxChatApp.ViewListOfUsersResponse
	(*ViewListOfChatRoomsRequest)(nil),  // 11: linuxChatApp.ViewListOfChatRoomsRequest
	(*ViewListOfChatRoomsResponse)(nil), // 12: linuxChatApp.ViewListOfChatRoomsResponse
}
var file_LinuxChatApp_proto_depIdxs = []int32{
	0,  // 0: linuxChatApp.LinuxChatAppService.CreateChatRoom:input_type -> linuxChatApp.CreateChatRoomRequest
	2,  // 1: linuxChatApp.LinuxChatAppService.JoinChatRoom:input_type -> linuxChatApp.JoinChatRoomRequest
	4,  // 2: linuxChatApp.LinuxChatAppService.LeaveChatRoom:input_type -> linuxChatApp.LeaveChatRoomRequest
	8,  // 3: linuxChatApp.LinuxChatAppService.SendMessage:input_type -> linuxChatApp.MessageRequest
	9,  // 4: linuxChatApp.LinuxChatAppService.ViewListOfUsers:input_type -> linuxChatApp.ViewListOfUsersRequest
	11, // 5: linuxChatApp.LinuxChatAppService.ViewListOfChatRooms:input_type -> linuxChatApp.ViewListOfChatRoomsRequest
	1,  // 6: linuxChatApp.LinuxChatAppService.CreateChatRoom:output_type -> linuxChatApp.CreateChatRoomResponse
	3,  // 7: linuxChatApp.LinuxChatAppService.JoinChatRoom:output_type -> linuxChatApp.JoinChatRoomResponse
	5,  // 8: linuxChatApp.LinuxChatAppService.LeaveChatRoom:output_type -> linuxChatApp.LeaveChatRoomResponse
	7,  // 9: linuxChatApp.LinuxChatAppService.SendMessage:output_type -> linuxChatApp.MessageResponse
	10, // 10: linuxChatApp.LinuxChatAppService.ViewListOfUsers:output_type -> linuxChatApp.ViewListOfUsersResponse
	12, // 11: linuxChatApp.LinuxChatAppService.ViewListOfChatRooms:output_type -> linuxChatApp.ViewListOfChatRoomsResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_LinuxChatApp_proto_init() }
func file_LinuxChatApp_proto_init() {
	if File_LinuxChatApp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_LinuxChatApp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinuxChatApp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinuxChatApp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinChatRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinuxChatApp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinChatRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinuxChatApp_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveChatRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinuxChatApp_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveChatRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinuxChatApp_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageRow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinuxChatApp_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinuxChatApp_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinuxChatApp_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewListOfUsersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinuxChatApp_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewListOfUsersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinuxChatApp_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewListOfChatRoomsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinuxChatApp_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewListOfChatRoomsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_LinuxChatApp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_LinuxChatApp_proto_goTypes,
		DependencyIndexes: file_LinuxChatApp_proto_depIdxs,
		MessageInfos:      file_LinuxChatApp_proto_msgTypes,
	}.Build()
	File_LinuxChatApp_proto = out.File
	file_LinuxChatApp_proto_rawDesc = nil
	file_LinuxChatApp_proto_goTypes = nil
	file_LinuxChatApp_proto_depIdxs = nil
}
